# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sales.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sales.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsales.proto\x12\x05sales\"A\n\x0bUploadChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x12\n\nauth_token\x18\x03 \x01(\t\"\x82\x01\n\x0eUploadResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x14\n\x0c\x64ownload_url\x18\x04 \x01(\t\x12)\n\x07metrics\x18\x05 \x01(\x0b\x32\x18.sales.ProcessingMetrics\"6\n\x10JobStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x12\n\nauth_token\x18\x02 \x01(\t\"\x8b\x01\n\x11JobStatusResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x14\n\x0c\x64ownload_url\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12)\n\x07metrics\x18\x05 \x01(\x0b\x32\x18.sales.ProcessingMetrics\"\x90\x01\n\x11ProcessingMetrics\x12\x1a\n\x12processing_time_ms\x18\x01 \x01(\x03\x12\x16\n\x0erows_processed\x18\x02 \x01(\x03\x12\x14\n\x0crows_skipped\x18\x03 \x01(\x03\x12\x19\n\x11\x64\x65partments_count\x18\x04 \x01(\x03\x12\x16\n\x0epeak_memory_mb\x18\x05 \x01(\x03\x32\x8b\x01\n\x0cSalesService\x12\x38\n\tUploadCSV\x12\x12.sales.UploadChunk\x1a\x15.sales.UploadResponse(\x01\x12\x41\n\x0cGetJobStatus\x12\x17.sales.JobStatusRequest\x1a\x18.sales.JobStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sales_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADCHUNK']._serialized_start=22
  _globals['_UPLOADCHUNK']._serialized_end=87
  _globals['_UPLOADRESPONSE']._serialized_start=90
  _globals['_UPLOADRESPONSE']._serialized_end=220
  _globals['_JOBSTATUSREQUEST']._serialized_start=222
  _globals['_JOBSTATUSREQUEST']._serialized_end=276
  _globals['_JOBSTATUSRESPONSE']._serialized_start=279
  _globals['_JOBSTATUSRESPONSE']._serialized_end=418
  _globals['_PROCESSINGMETRICS']._serialized_start=421
  _globals['_PROCESSINGMETRICS']._serialized_end=565
  _globals['_SALESSERVICE']._serialized_start=568
  _globals['_SALESSERVICE']._serialized_end=707
# @@protoc_insertion_point(module_scope)
