# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sales_pb2 as sales__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sales_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SalesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadCSV = channel.stream_unary(
                '/sales.SalesService/UploadCSV',
                request_serializer=sales__pb2.UploadChunk.SerializeToString,
                response_deserializer=sales__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/sales.SalesService/GetJobStatus',
                request_serializer=sales__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=sales__pb2.JobStatusResponse.FromString,
                _registered_method=True)


class SalesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadCSV(self, request_iterator, context):
        """Client-streaming: upload CSV file chunk by chunk
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Check job status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SalesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadCSV': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadCSV,
                    request_deserializer=sales__pb2.UploadChunk.FromString,
                    response_serializer=sales__pb2.UploadResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=sales__pb2.JobStatusRequest.FromString,
                    response_serializer=sales__pb2.JobStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sales.SalesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sales.SalesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SalesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadCSV(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/sales.SalesService/UploadCSV',
            sales__pb2.UploadChunk.SerializeToString,
            sales__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sales.SalesService/GetJobStatus',
            sales__pb2.JobStatusRequest.SerializeToString,
            sales__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
